services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - path: .env
        required: true
    environment:
      DATABASE_URL: 'postgres://postgres:postgres@db:5432/supermod-registry?schema=public'
      R2_ACCOUNT_ID: ''
      R2_ACCESS_KEY_ID: ''
      R2_SECRET_ACCESS_KEY: ''
      R2_BUCKET: 'bucket-name'
      CDN_URL: 'https://your-domain.com'
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  pgdata: