services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - path: .env
        required: true
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  pgdata:
